def show():
    print()
    print("               Get Facebook Cookies and Access Token v1.5.3")
    print("   _            __     __  _ _             __          __  _     ")
    print("  | |           \ \   / / | | |            \ \        / / | |    ")
    print("  | |__  _   _   \ \_/ /__| | | _____      _\ \  /\  / /__| |__  ")
    print("  | '_ \| | | |   \   / _ \ | |/ _ \ \ /\ / /\ \/  \/ / _ \ '_ \ ")
    print("  | |_) | |_| |    | |  __/ | | (_) \ V  V /  \  /\  /  __/ |_) |")
    print("  |_.__/ \__, |    |_|\___|_|_|\___/ \_/\_/    \/  \/ \___|_.__/ ")
    print("          __/ |                                                  ")
    print("         |___/             https://yellowweb.top                 ")
    print()
    print("If you like this script, PLEASE DONATE!")
    print("USDT TRC20: TKeNEVndhPSKXuYmpEwF4fVtWUvfCnWmra")
    print("Bitcoin: bc1qqv99jasckntqnk0pkjnrjtpwu0yurm0qd0gnqv")
    print("Ethereum: 0xBC118D3FDE78eE393A154C29A4545c575506ad6B")
    print()
    print("ONLY IF you donate, you are allowed to ask questions.")
    print("Telegram: @dvygolov")
    print()
